/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

export interface Config {
  collections: {
    users: User;
    media: Media;
    experiences: Experience;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  globals: {};
  user: User & {
    collection: 'users';
  };
  db: {
    defaultIDType: string;
  };
  auth: {
    users: UserAuthOperations;
  };
  locale: null;
}
export interface User {
  id: string;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  password?: string | null;
}
export interface Media {
  id: string;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
export interface Experience {
  id: string;
  title: string;
  subtitle: string;
  price: number;
  duration: string;
  description: string;
  gradient: string;
  color: string;
  icon: string;
  sessions: string;
  features?:
    | {
        feature: string;
        id?: string | null;
      }[]
    | null;
  locations?:
    | {
        location: string;
        id?: string | null;
      }[]
    | null;
  detailedInfo: {
    overview: string;
    whatYouGet?:
      | {
          item: string;
          id?: string | null;
        }[]
      | null;
    process?:
      | {
          step: string;
          id?: string | null;
        }[]
      | null;
    locations?:
      | {
          location: string;
          id?: string | null;
        }[]
      | null;
    requirements?:
      | {
          requirement: string;
          id?: string | null;
        }[]
      | null;
  };
  updatedAt: string;
  createdAt: string;
}
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}
